//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADGV.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ADGVStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ADGVStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADGV.Localization.ADGVStrings", typeof(ADGVStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancelbutton_text {
            get {
                return ResourceManager.GetString("cancelbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar filtro.
        /// </summary>
        internal static string cancelfiltermenuitem_text {
            get {
                return ResourceManager.GetString("cancelfiltermenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpiar Ordenar Por.
        /// </summary>
        internal static string cancelsortmenuitem_text {
            get {
                return ResourceManager.GetString("cancelsortmenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string checknodetree_hour {
            get {
                return ResourceManager.GetString("checknodetree_hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        internal static string checknodetree_millisecond {
            get {
                return ResourceManager.GetString("checknodetree_millisecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string checknodetree_minute {
            get {
                return ResourceManager.GetString("checknodetree_minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string checknodetree_second {
            get {
                return ResourceManager.GetString("checknodetree_second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro por fecha.
        /// </summary>
        internal static string filtersmenuitem_text_datetime {
            get {
                return ResourceManager.GetString("filtersmenuitem_text_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro numerico.
        /// </summary>
        internal static string filtersmenuitem_text_numeric {
            get {
                return ResourceManager.GetString("filtersmenuitem_text_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtro por texto.
        /// </summary>
        internal static string filtersmenuitem_text_text {
            get {
                return ResourceManager.GetString("filtersmenuitem_text_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enero.
        /// </summary>
        internal static string month1 {
            get {
                return ResourceManager.GetString("month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octubre.
        /// </summary>
        internal static string month10 {
            get {
                return ResourceManager.GetString("month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noviembre.
        /// </summary>
        internal static string month11 {
            get {
                return ResourceManager.GetString("month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diciembre.
        /// </summary>
        internal static string month12 {
            get {
                return ResourceManager.GetString("month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Febrero.
        /// </summary>
        internal static string month2 {
            get {
                return ResourceManager.GetString("month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marzo.
        /// </summary>
        internal static string month3 {
            get {
                return ResourceManager.GetString("month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abril.
        /// </summary>
        internal static string month4 {
            get {
                return ResourceManager.GetString("month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayo.
        /// </summary>
        internal static string month5 {
            get {
                return ResourceManager.GetString("month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Junio.
        /// </summary>
        internal static string month6 {
            get {
                return ResourceManager.GetString("month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Julio.
        /// </summary>
        internal static string month7 {
            get {
                return ResourceManager.GetString("month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agosto.
        /// </summary>
        internal static string month8 {
            get {
                return ResourceManager.GetString("month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Septiembre.
        /// </summary>
        internal static string month9 {
            get {
                return ResourceManager.GetString("month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string okbutton_text {
            get {
                return ResourceManager.GetString("okbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string setfilterform_andlabel_text {
            get {
                return ResourceManager.GetString("setfilterform_andlabel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string setfilterform_cancelbutton_text {
            get {
                return ResourceManager.GetString("setfilterform_cancelbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar filas donde el valor.
        /// </summary>
        internal static string setfilterform_columnnamelabel_text {
            get {
                return ResourceManager.GetString("setfilterform_columnnamelabel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor no válido.
        /// </summary>
        internal static string setfilterform_errorprovider_value {
            get {
                return ResourceManager.GetString("setfilterform_errorprovider_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A más tardar.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_after {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_after", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antes de lo.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_before {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comienza con.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_begins {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_begins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entre.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_between {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contiene.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_contain {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_contain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termina con.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_ends {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_ends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es igual a.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_equal {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor que o igual a.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_lagerequals {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_lagerequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayor que.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_larger {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor que.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_less {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menor que o igual a.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_lessequals {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_lessequals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No comienza con.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_nobegins {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_nobegins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contiene.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_nocontain {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_nocontain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No termina con.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_noends {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_noends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no es igual a.
        /// </summary>
        internal static string setfilterform_filtertypecombobox_notequal {
            get {
                return ResourceManager.GetString("setfilterform_filtertypecombobox_notequal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string setfilterform_okbutton_text {
            get {
                return ResourceManager.GetString("setfilterform_okbutton_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar filtro.
        /// </summary>
        internal static string setfilterform_text {
            get {
                return ResourceManager.GetString("setfilterform_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string setfilterform_viewfilterstring_and {
            get {
                return ResourceManager.GetString("setfilterform_viewfilterstring_and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrar filas donde el valor.
        /// </summary>
        internal static string setfilterform_viewfilterstring_mustbe {
            get {
                return ResourceManager.GetString("setfilterform_viewfilterstring_mustbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string setupfiltermenuitem_text {
            get {
                return ResourceManager.GetString("setupfiltermenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por Falso / Verdadero.
        /// </summary>
        internal static string sortascmenuitem_text_boolean {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort oldest to newest.
        /// </summary>
        internal static string sortascmenuitem_text_datetime {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort smallest to largest.
        /// </summary>
        internal static string sortascmenuitem_text_numeric {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar А a Z.
        /// </summary>
        internal static string sortascmenuitem_text_text {
            get {
                return ResourceManager.GetString("sortascmenuitem_text_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar Z a A.
        /// </summary>
        internal static string sortdescmenuitem_text {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar por Verdadero / Falso.
        /// </summary>
        internal static string sortdescmenuitem_text_boolean {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text_boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar reciente al más antiguo.
        /// </summary>
        internal static string sortdescmenuitem_text_datetime {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text_datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenar de mayor a menor.
        /// </summary>
        internal static string sortdescmenuitem_text_numeric {
            get {
                return ResourceManager.GetString("sortdescmenuitem_text_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ( Seleccionar todo).
        /// </summary>
        internal static string tripletreenode_allnode_text {
            get {
                return ResourceManager.GetString("tripletreenode_allnode_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falso.
        /// </summary>
        internal static string tripletreenode_boolean_false {
            get {
                return ResourceManager.GetString("tripletreenode_boolean_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdadero.
        /// </summary>
        internal static string tripletreenode_boolean_true {
            get {
                return ResourceManager.GetString("tripletreenode_boolean_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Espacios en blanco).
        /// </summary>
        internal static string tripletreenode_nullnode_text {
            get {
                return ResourceManager.GetString("tripletreenode_nullnode_text", resourceCulture);
            }
        }
    }
}
